<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="dev"
    errors="1" failures="0" hostname="" id="" package="dev" skipped="0"
    tests="1" time="1.901" timestamp="">
  
    <testcase name="Dev.to" classname="dev" time="1.901" assertions="2">

    

    
      <errortype="error">Error
    at Object.Dev.to (D:\Anul IV Semestrul II\selenium\test\dev.js:9:10)
    at Context.call (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\context.js:379:35)
    at TestCase.run (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\testcase.js:49:31)
    at Runnable.handleRunnable [as __runFn] (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\index.js:374:80)
    at Runnable.run (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\runnable.js:123:21)
    at TestSuite.createRunnable (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\index.js:441:33)
    at TestSuite.handleRunnable (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\index.js:446:18)
    at createSession.then.then._ (D:\Anul IV Semestrul II\selenium\node_modules\nightwatch\lib\testsuite\index.js:374:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)</error>
    
    </testcase>
  

  
    <system-err>
      [0;31m  Error: Error while running &#34;setValue&#34; command: &#34;Error: setValue method expects 3 (or 4 if using implicit &#34;css selector&#34; strategy) arguments - 2 given.
  &#34;[0m
[0;90m       at Object.Dev.to (D:\Anul IV Semestrul II\selenium\test\dev.js:9:10)
       at process._tickCallback (internal/process/next_tick.js:68:7)[0m
    </system-err>
  

  
  </testsuite>
</testsuites>
